name: build production code

on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build the block source code
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'dist'
          # The message for the commit.
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'Your commit message'
          pull: 'NO-PULL'
